### ISSUE TITLE
Design Find modal + add content 

### ISSUE THREAD

**Issue by snrelghgub** [chingu-voyages/v9-toucans-team-12#10]
display picture & item name, description, the contact details of the person donating (name, phone, address, email) for each item available for collection from a donor 
requirement to be met: user shall be able to simply scroll through & find items they need & wish to collect from another user

-use javascript
-nice scroll

**Comment by ashiyaman** [comment]
Hi team, 
I have shared the collection of items over the discord channel. Please review it and let me know what you think about it

**Comment by snrelghgub** [comment]
hi ashiya, I left you feedback in our discord channel (you did an amazing job - thanks so much for your amazing effort here). if you need a hand with anything for this issue / section of the page I cannot straightaway during the weekend but can make time on Mon or Tues, plz don't hesitate to let me know :)

**Comment by ashiyaman** [comment]
I have merged with the develop branch
