### ISSUE TITLE
Issue on one of the requirements 

### ISSUE THREAD

**Issue by DrewDen** [chingu-voyages/v9-toucans-team-12#17]
Hello team.  I wanted to bring up a potential issue with one of the requirements for our site. 
For one of the requirements, it states that the user would be highly encouraged and motivated to donate and find items.  

My question would be how would we accomplish this on our site.  
Ideas that come to mind would be; 
A call to action maybe we will accept your first donation on us to get them interested in how it works.
Maybe our design of the site will speak for itself.
Maybe the about me section will intense them to try it out.

These are some of my ideas for this issue.  I would love to hear your guys input over this matter.

**Comment by ashiyaman** [comment]
Since we already discussed that the layout of our website and the call for action buttons would serve this purpose, Im closing this issue
