### ISSUE TITLE
Headers are not resized properly in mobile view (450px or less) 

### ISSUE THREAD

**Issue by snrelghgub** [chingu-voyages/v9-toucans-team-12#37]
there is an issue with the media query we wrote which is supposed to update the headers of the about-us, how-it-work & contact-us sections of our page. I noticed that the only header which is resized & made smaller properly in mobile view is the about-us only, the other headers aren't resized properly

**Comment by DrewDen** [comment]
I found the issues for why this is not working right.  The element on the about us is an h2.  The elements of how it works and contact are h1 elements.  The media query is set up for all h2 elements.  The media query works fine we just need to change the other elements to h2.
