### ISSUE TITLE
Collect display content for Find modal page 

### ISSUE THREAD

**Issue by snrelghgub** [chingu-voyages/v9-toucans-team-12#9]
-create a nice & wide range of item donations with display picture & item name, description, the contact details of the person donating (name, phone, address, email)
-there is no need to code here, just gather a nice range of items to be used for display in the Find modal page
-this will help to meet the following requirement: user shall be able to simply scroll through & find items they need & wish to collect from another user

**Comment by ashiyaman** [comment]
Hi team,
I have shared the link for the images of donated items in our channel... Please review that and let me know if its good to go
